### ISSUE TITLE
Возможность ответа и пересылки сообщений

### ISSUE THREAD

**Issue by Russia9** [danyadev/vk-desktop#26]
## Описание
Добавить возможность ответа и пересылки сообщений

## Внешний вид
Ответ на сообщение:
![изображение](https://user-images.githubusercontent.com/33428293/69911404-17490780-142c-11ea-83ee-166d43b6abd6.png)

Пересылка и ответ:
![изображение](https://user-images.githubusercontent.com/33428293/69911399-09938200-142c-11ea-8c19-ef7de2e46b83.png)

**Comment by danyadev** [comment]
Реализовано.
