### ISSUE TITLE
Отображение меню выбора эмодзи

### ISSUE THREAD

**Issue by Russia9** [danyadev/vk-desktop#27]
## Описание
Отображение меню выбора эмодзи по нажатию на кнопку возле message input. Сейчас она ничего не делает.
![изображение](https://user-images.githubusercontent.com/33428293/69911425-6ee77300-142c-11ea-8014-76c924ee2f9c.png)

## Внешний вид
![изображение](https://user-images.githubusercontent.com/33428293/69911417-55462b80-142c-11ea-9b42-f4a9792d1f77.png)

**Comment by danyadev** [comment]
Запланированная фича
