### ISSUE TITLE
Не пропадает модальное окно после выхода из аккаунта

### ISSUE THREAD

**Issue by MrZillaGold** [danyadev/vk-desktop#30]
## Описание
После выхода из аккаунта остается модальное окно. 

Необходимо вызывать closeModal в logout.
https://github.com/danyadev/vk-desktop/blob/55e77e5d77bb54b50db7a30ecf5151c34f8e0f3a/src/components/modals/Logout.vue#L23

![image](https://user-images.githubusercontent.com/42776347/74715302-eaaccb00-5277-11ea-825b-74b6d9b64442.png)

**Comment by danyadev** [comment]
Сама проблема заключается не в скрытии модального окна, а в преждевременном отображении страницы авторизации (до перезагрузки страницы)
