### ISSUE TITLE
Ошибка доступа к Program Files на Windows

### ISSUE THREAD

**Issue by slmatthew** [danyadev/vk-desktop#32]
При установке приложения возникает ошибка доступа к папке Program Files

![image](https://user-images.githubusercontent.com/36668268/75072071-c5ce8700-5507-11ea-8c19-1345b0065aa4.png)

## Шаги для воспроизведения
1. Скачать установщик для винды из [последнего релиза](https://github.com/danyadev/vk-desktop/releases/latest)
2. Запустить установщик

## Информация о системе
- windows 10 x64
- vk desktop 0.2.0

**Comment by danyadev** [comment]
Исправлено в 17afd15. Теперь приложение устанавливается в папку AppData\Local\VK Desktop
