### ISSUE TITLE
Шаблоны сообщения

### ISSUE THREAD

**Issue by slmatthew** [danyadev/vk-desktop#33]
Предлагаю сделать такую же фичу, как в VK Messenger: при нажатии на ПКМ в окне ввода сообщения, будет открываться контекстное меню, в котором будут некие шаблоны сообщений. Можно сделать его настраиваемым.

![image](https://user-images.githubusercontent.com/36668268/75096021-1dbec980-55ac-11ea-9cf8-a5c9a21edae6.png)

**Comment by slmatthew** [comment]
ну в общем хочю кноп*очку*

![image](https://user-images.githubusercontent.com/36668268/75448763-e0c44f80-597c-11ea-880a-3cc4e4e76bd0.png)

**Comment by danyadev** [comment]
Не думаю, что подобная фича будет в скором времени реализована.
