### ISSUE TITLE
С некоторого момента при старте отображается просто пустое окно

### ISSUE THREAD

**Issue by nerzhulart** [danyadev/vk-desktop#42]
## Описание

![image](https://user-images.githubusercontent.com/623624/83642837-01252b00-a5b8-11ea-95a9-c4a33a3af43c.png)

Натыкаюсь уже на такое дважды. Первый раз помогло удалить полностью директорию из AppData/Roaming. Сейчас не помогает вообще.

Система: Свежеустановленная Windows 10 2004.
Если нужны какие то логи - могу прикрепить, с ходу не нашел

**Comment by danyadev** [comment]
Это версия из релизов или собранная из исходников?

**Comment by nerzhulart** [comment]
> Это версия из релизов или собранная из исходников?

релизная из официальной группы

**Comment by danyadev** [comment]
Мне кажется, что проблему я уже исправил, когда перешел на новую версию Electron, так что если собрать приложение из исходников то все должно заработать

**Comment by nerzhulart** [comment]
> Мне кажется, что проблему я уже исправил, когда перешел на новую версию Electron, так что если собрать приложение из исходников то все должно заработать.
> 
> Однако эта версия не совсем стабильна, а следующий релиз будет неизвестно когда.

попробовал поставить из релизов выложенных здесь, весьма симпатично выглядит, но конечно много чего не работает.
Для этого бага воркэрануда нет никакого?

**Comment by danyadev** [comment]
Неа, я и не знал, что такое вообще может случиться
Остается только ждать релиза, но он выйдет минимум в июле, я думаю
