### ISSUE TITLE
Не происходит переход к концу диалога

### ISSUE THREAD

**Issue by CleFerMy** [danyadev/vk-desktop#5]
Шаги воспроизведения:

1. Открыть список диалогов
2. Прочитать все сообщения какого-то диалога (с другого устройства или приложения)
3. Перейти в этот диалог

ОР: произойдёт переход к концу диалога, т.к он прочитан
ФР: покажет первые сообщения

P.S под первыми сообщениями подразумеваются те сообщения, которые были загружены при включении либо последние прочитанные с VK Desktop

**Comment by danyadev** [comment]
Снова воспроизводится
