### ISSUE TITLE
Вставка изображений

### ISSUE THREAD

**Issue by ItzNeviKat** [danyadev/vk-desktop#52]
## Описание
- Прикрепление изображения к сообщению при нажатии Ctrl (Cmd) + V, если в буфере обмена есть изображение. Это реализовано на сайте ВК и в VK Messenger.

**Comment by danyadev** [comment]
К сожалению запланированные фичи сложно назвать багом

**Comment by ItzNeviKat** [comment]
> К сожалению запланированные фичи сложно назвать багом

Это не баг, это Feature Request.
