### ISSUE TITLE
Бесконечный вход

### ISSUE THREAD

**Issue by AdisAlagic** [danyadev/vk-desktop#61]
## Описание
Не могу войти в приложение. Логи показывают, что токен для Android был взят, токен для Desktop взять не может. Делает запрос каждую миллисекунду или тик, тем самым не успевая получить ответ.

## Шаги для воспроизведения
Попытка войти в аккаунт первый раз через кнопку "Войти", меню авторизации

## Ожидаемый результат
Я вошел в аккаунт

## Полученный результат
Завис на странице авторизации.

## Информация о системе
Windows 10 Версия 10.0.19042 Сборка 19042

Версия приложения: 0.3.0

Node.js v12.16.1.

**Comment by danyadev** [comment]
Можно сами логи?

**Comment by danyadev** [comment]
Я примерно понял, в чем может быть проблема, но мне нужна твоя помощь для точной установки проблемы

Наверное проще будет написать мне в ВК (vk.com/danyadev)
