### ISSUE TITLE
Add option to select window buttons location

### ISSUE THREAD

**Issue by melianmiko** [danyadev/vk-desktop#65]
# Описание
У меня в системе (Linux, Gnome Shell) кнопки управления окном перенесены в левую часть заголовка (как в MacOS). Хотелось бы иметь возможность также перенести их туда в этом приложении.

**Comment by melianmiko** [comment]
![image](https://user-images.githubusercontent.com/67851274/149615613-51fbdf67-930d-412d-aa9b-85fdb9045fcb.png)

**Comment by danyadev** [comment]
Теперь в настройках есть возможность включить нативный тайтлбар, и мне интересно посмотреть, как же он будет у тебя выглядеть

**Comment by melianmiko** [comment]
> интересно посмотреть, как же он будет у тебя выглядеть

Вполне неплохо выглядит. Да и главное что удобнее, не нужно думать где там эти кнопки. Спасибо =)

![image](https://user-images.githubusercontent.com/67851274/149736752-73acf616-cd81-4dd2-8599-150e2583ca50.png)

**Comment by danyadev** [comment]
осталось темную тему сделать)))
есть открытый pull request, и его в принципе можно развить

**Comment by melianmiko** [comment]
Я бы помог,но с Vue совсем не знаком. Да и времени свободного не так много...

**Comment by danyadev** [comment]
у меня попа боль только с подбором цветов для темной темы, сам не знаю, какие хочу

**Comment by melianmiko** [comment]
Сделай несколько вариантов, как тут, на гитхабе. Домустим, тёмно-синий (как в офф мессенджере вк), серый и чёрный. Как пример.
