### ISSUE TITLE
Не сбрасывается счетчик сообщений чата

### ISSUE THREAD

**Issue by Anonym-tsk** [danyadev/vk-desktop#67]
## Описание

Не сбрасывается счетчик сообщений чата при переходе в чат

## Шаги для воспроизведения
Открыть чат, пролистать до конца, счетчик не сбросится

## Информация о системе

Название и версия системы: MacOS Monterey, M1
Версия приложения: [0.3.2](https://github.com/danyadev/vk-desktop/releases/tag/0.3.2)

**Comment by danyadev** [comment]
Скорее всего ты просто не выключил нечиталку сообщений
<img width="347" alt="image" src="https://user-images.githubusercontent.com/35631027/158559062-62adbdde-fc90-414a-90fb-89964b3df894.png">
