### ISSUE TITLE
Иногда сообщение не помечаются как прочитанные

### ISSUE THREAD

**Issue by godlikeSwan** [danyadev/vk-desktop#71]
Не знаю, баг или фича, но после переключения с диалога на диалог или после переключения окон windows сообщения перестают помечаться как прочитанные даже после скролла до самого низу

**Comment by godlikeSwan** [comment]
Заглянул в закрытые issue, увидел про нечиталку
думаю, стоит добавить в readme

**Comment by danyadev** [comment]
В мастере сейчас находится версия, где:
— нечиталка по умолчанию выключена
— нет нижней и левой менюшек, где сразу была видна кнопка настроек, и теперь она перенесена в те же три точки

<img width="338" alt="image" src="https://user-images.githubusercontent.com/35631027/160267400-2731129a-368e-4db4-a14f-6807c832635f.png">
