### ISSUE TITLE
Ошибка при попытке запустить приложение

### ISSUE THREAD

**Issue by TofaDev** [danyadev/vk-desktop#75]
## Описание

Невозможно запустить программу

лог ошибки:

`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[250634:0816/234233.376468:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Ловушка трассировки/останова (стек памяти сброшен на диск)
`

**UPD**: Логи по пути `~/.config/vk-desktop/logs/` отсутствуют

## Шаги для воспроизведения

chmod u+x vk-desktop
./vk-desktop

## Информация о системе

Название и версия системы: Ubuntu 22.04, Gnome 42
Версия приложения:  0.3.2

UPD: 

Я смог запустить приложение с флагом --no-sandbox, но приложение по прежнему не работает:

![изображение](https://user-images.githubusercontent.com/94196761/187450689-da3c3670-dd33-4b1d-9d61-a5bbdb78590e.png)

**Comment by Jamolov-Bejan** [comment]
у меня тоже  это праоблема

**Comment by danyadev** [comment]
Проверяйте, вышел новый релиз
