### ISSUE TITLE
Переместить каунтер сообщений в нижнюю полосу в элементе списка чата

### ISSUE THREAD

**Issue by danyadev** [danyadev/vk-desktop#93]
как сейчас:
<img width="385" alt="image" src="https://github.com/user-attachments/assets/88d473a5-8f65-4c9b-971e-e797fb166a95">

пример, как должно быть:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/5fb6a94c-cee6-4f19-98d1-feef4cacd77d">

**Comment by Binatik** [comment]
Stopped => #94
